# Generated by Django 3.2.9 on 2021-11-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='miles',
        ),
    ]
